configuration:
  - --version 5.20.1.1
  - --version 5.24.1.1

install:
  - choco install --allowemptychecksum strawberryperl %configuration%
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  
build_script:
  - perl term-readkey.pl
