install:
  - choco install --allowemptychecksum strawberryperl
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  
build_script:
  - perl -MTerm::ReadKey -E "say $Term::ReadKey::VERSION"
