install:
  - choco install --allowemptychecksum strawberryperl
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  
build_script:
  - cpanm -v Term::ReadKey@2.31
  - perl term-readkey.pl